
name: Clone Public Repository Workflow

on:
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
    
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: jtcortex/mdsamples PUBLIC repository
        uses: jtcorc01/mdsample@main
        with:
          owner: 'jtcortex'
          repository: 'mdsample'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd mdsample
          ls -la
